package mc_vultr_gov

const TELEGRAM_TOKEN_KEY = "TELEGRAM_TOKEN"
const ALLOWED_CHATS_KEY = "ALLOWED_CHATS"

const RCON_PASSWORD_KEY = "RCON_PASSWORD"

const VULTR_API_KEY_KEY = "VULTR_API_KEY"
const TARGET_INSTANCE_LABEL_KEY = "TARGET_INSTANCE_LABEL"
const TARGET_INSTANCE_REGION_KEY = "TARGET_INSTANCE_REGION"
const TARGET_INSTANCE_PLAN_KEY = "TARGET_INSTANCE_PLAN"
const TARGET_INSTANCE_OS_ID_KEY = "TARGET_INSTANCE_OS_ID"
const TARGET_SCRIPT_ID_KEY = "TARGET_SCRIPT_ID"
const TARGET_BLOCK_LABEL_KEY = "TARGET_BLOCK_LABEL"
